// ---------------------------------------------
// PRODUCT DATA
// In a real app this would come from a database/API.
// Here it's a static array so the whole site works
// as pure front-end (no backend required).
// ---------------------------------------------

const PRODUCTS = [
  {
    id: 1,
    brand: "Apple",
    name: "iPhone 15",
    tagline: "A16 Bionic chip, 48MP camera",
    price: 74900,
    originalPrice: 79900,
    color: "#1F2937",
    accent: "#A3AAB5",
    rating: 4.6,
    reviews: 2431,
    badge: "Bestseller",
    ram: "6GB",
    storage: "128GB",
    display: "6.1\" Super Retina XDR",
    battery: "3349 mAh",
    camera: "48MP + 12MP Dual Camera",
    processor: "Apple A16 Bionic",
    description:
      "The iPhone 15 brings the powerful A16 Bionic chip, a 48MP main camera for stunningly detailed photos, and Dynamic Island to the mainstream lineup, wrapped in a durable color-infused glass and aluminum design.",
  },
  {
    id: 2,
    brand: "Samsung",
    name: "Galaxy S24",
    tagline: "Galaxy AI, 50MP camera, 120Hz display",
    price: 64999,
    originalPrice: 79999,
    color: "#26344A",
    accent: "#7FA6D9",
    rating: 4.5,
    reviews: 1876,
    badge: "18% off",
    ram: "8GB",
    storage: "256GB",
    display: "6.2\" Dynamic AMOLED 2X, 120Hz",
    battery: "4000 mAh",
    camera: "50MP Triple Camera with AI",
    processor: "Exynos 2400",
    description:
      "Galaxy S24 packs Galaxy AI features like live translate and circle-to-search, a bright 120Hz AMOLED display, and a versatile triple-camera system in a compact titanium-edged frame.",
  },
  {
    id: 3,
    brand: "OnePlus",
    name: "OnePlus 12",
    tagline: "Snapdragon 8 Gen 3, 100W charging",
    price: 64999,
    originalPrice: 69999,
    color: "#7A1F2B",
    accent: "#E8B4B8",
    rating: 4.5,
    reviews: 1042,
    badge: "Fast Charging",
    ram: "12GB",
    storage: "256GB",
    display: "6.82\" LTPO AMOLED, 120Hz",
    battery: "5400 mAh",
    camera: "50MP Hasselblad Triple Camera",
    processor: "Snapdragon 8 Gen 3",
    description:
      "OnePlus 12 combines flagship Snapdragon 8 Gen 3 performance with a Hasselblad-tuned camera system and blazing 100W SUPERVOOC charging that takes the phone from 1% to 100% in under half an hour.",
  },
  {
    id: 4,
    brand: "Google",
    name: "Pixel 8",
    tagline: "Best-in-class computational photography",
    price: 52999,
    originalPrice: 59999,
    color: "#3D4A3D",
    accent: "#B8CDB8",
    rating: 4.4,
    reviews: 897,
    badge: "AI Camera",
    ram: "8GB",
    storage: "128GB",
    display: "6.2\" Actua OLED, 120Hz",
    battery: "4575 mAh",
    camera: "50MP Dual Camera with AI",
    processor: "Google Tensor G3",
    description:
      "Pixel 8 is built around Google's Tensor G3 chip and industry-leading computational photography — Magic Eraser, Best Take, and Night Sight combine to make every shot look professionally edited.",
  },
  {
    id: 5,
    brand: "Xiaomi",
    name: "Redmi Note 13 Pro",
    tagline: "200MP camera, curved AMOLED display",
    price: 24999,
    originalPrice: 28999,
    color: "#1E3A5F",
    accent: "#8FB8E0",
    rating: 4.3,
    reviews: 3120,
    badge: "Bestseller",
    ram: "8GB",
    storage: "256GB",
    display: "6.67\" Curved AMOLED, 120Hz",
    battery: "5100 mAh",
    camera: "200MP OIS Triple Camera",
    processor: "Snapdragon 7s Gen 2",
    description:
      "Redmi Note 13 Pro punches well above its price with a 200MP OIS-stabilized camera, a gorgeous curved AMOLED panel, and 67W fast charging — making it one of the best value phones in its segment.",
  },
  {
    id: 6,
    brand: "Realme",
    name: "Realme 12 Pro+",
    tagline: "Periscope telephoto zoom camera",
    price: 29999,
    originalPrice: 33999,
    color: "#5B2C6F",
    accent: "#C9A8D8",
    rating: 4.2,
    reviews: 654,
    badge: "New Launch",
    ram: "8GB",
    storage: "128GB",
    display: "6.7\" Curved AMOLED, 120Hz",
    battery: "5000 mAh",
    camera: "50MP Periscope Telephoto",
    processor: "Snapdragon 7s Gen 2",
    description:
      "Realme 12 Pro+ stands out with a periscope telephoto lens rarely seen at this price, delivering true 3x optical zoom alongside a premium leather-textured back and vegan leather finish.",
  },
  {
    id: 7,
    brand: "Vivo",
    name: "Vivo V29",
    tagline: "Aura Light portrait photography",
    price: 32999,
    originalPrice: 35999,
    color: "#B8860B",
    accent: "#F0D890",
    rating: 4.3,
    reviews: 512,
    badge: "5% off",
    ram: "8GB",
    storage: "128GB",
    display: "6.78\" Curved AMOLED, 120Hz",
    battery: "4600 mAh",
    camera: "50MP OIS with Aura Light",
    processor: "Snapdragon 778G",
    description:
      "Vivo V29 is designed for portrait lovers, with a color-adaptive Aura ring light around the front camera and OIS-stabilized rear sensor that keeps low-light portraits sharp and well-lit.",
  },
  {
    id: 8,
    brand: "Apple",
    name: "iPhone 15 Pro",
    tagline: "Titanium design, A17 Pro chip",
    price: 134900,
    originalPrice: 139900,
    color: "#3B3B3D",
    accent: "#C4C4C7",
    rating: 4.8,
    reviews: 1654,
    badge: "Premium",
    ram: "8GB",
    storage: "256GB",
    display: "6.1\" Super Retina XDR ProMotion",
    battery: "3274 mAh",
    camera: "48MP Pro Camera System",
    processor: "Apple A17 Pro",
    description:
      "iPhone 15 Pro introduces a lightweight titanium frame, the customizable Action Button, and the A17 Pro chip — Apple's most powerful mobile chip yet — built for console-quality gaming and pro-level photography.",
  },
  {
    id: 9,
    brand: "Samsung",
    name: "Galaxy S24 Ultra",
    tagline: "S Pen, 200MP camera, titanium frame",
    price: 129999,
    originalPrice: 134999,
    color: "#1A1A2E",
    accent: "#9B9BC4",
    rating: 4.7,
    reviews: 2087,
    badge: "Flagship",
    ram: "12GB",
    storage: "256GB",
    display: "6.8\" Dynamic AMOLED 2X, 120Hz",
    battery: "5000 mAh",
    camera: "200MP Quad Camera",
    processor: "Snapdragon 8 Gen 3 for Galaxy",
    description:
      "Galaxy S24 Ultra is Samsung's most capable phone — a titanium-framed flagship with a built-in S Pen, a 200MP main sensor, and Galaxy AI features that redefine what's possible on a smartphone.",
  },
  {
    id: 10,
    brand: "Xiaomi",
    name: "Redmi 13C",
    tagline: "Budget-friendly everyday performer",
    price: 9999,
    originalPrice: 11999,
    color: "#2D6A4F",
    accent: "#95D5B2",
    rating: 4.0,
    reviews: 4521,
    badge: "Budget Pick",
    ram: "4GB",
    storage: "128GB",
    display: "6.74\" HD+ Display",
    battery: "5000 mAh",
    camera: "50MP AI Triple Camera",
    processor: "MediaTek Helio G85",
    description:
      "Redmi 13C is built for everyday essentials — calls, browsing, and social media — with a large battery, spacious display, and dependable performance at one of the most accessible price points in the lineup.",
  },
  {
    id: 11,
    brand: "OnePlus",
    name: "OnePlus Nord CE 3",
    tagline: "Balanced mid-ranger with fast charging",
    price: 22999,
    originalPrice: 26999,
    color: "#154360",
    accent: "#85C1E9",
    rating: 4.2,
    reviews: 1289,
    badge: "10% off",
    ram: "8GB",
    storage: "128GB",
    display: "6.7\" Fluid AMOLED, 120Hz",
    battery: "5000 mAh",
    camera: "50MP Sony Sensor Camera",
    processor: "Snapdragon 782G",
    description:
      "Nord CE 3 keeps the essentials of the OnePlus experience — clean software, a smooth 120Hz display, and 80W fast charging — in a more accessible mid-range package.",
  },
  {
    id: 12,
    brand: "Google",
    name: "Pixel 8 Pro",
    tagline: "Pro-grade cameras, 7 years of updates",
    price: 106999,
    originalPrice: 112999,
    color: "#2C2C34",
    accent: "#B0AEC4",
    rating: 4.6,
    reviews: 743,
    badge: "Flagship",
    ram: "12GB",
    storage: "256GB",
    display: "6.7\" Super Actua LTPO OLED",
    battery: "5050 mAh",
    camera: "50MP Pro Triple Camera",
    processor: "Google Tensor G3",
    description:
      "Pixel 8 Pro adds a telephoto lens, a temperature sensor, and Pro-exclusive camera controls to the Pixel lineup, backed by Google's promise of 7 years of OS, security, and Feature Drop updates.",
  },
];

// ---------------------------------------------
// Helper: format a number as Indian Rupees
// ---------------------------------------------
function formatPrice(num) {
  return "₹" + num.toLocaleString("en-IN");
}

// ---------------------------------------------
// Helper: get a single product by id
// ---------------------------------------------
function getProductById(id) {
  return PRODUCTS.find((p) => p.id === Number(id));
}
